# Generated by Django 6.0.2 on 2026-02-25 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.IntegerField(max_length=15, unique=True)),
                ('address', models.CharField(max_length=30)),
                ('speciallization', models.CharField(max_length=30)),
                ('Quallification', models.CharField(max_length=20)),
                ('registration_no', models.CharField(max_length=10, unique=True)),
                ('available_days', models.JSONField()),
                ('slot_duration', models.IntegerField(default=30)),
                ('available_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.IntegerField(max_length=15, unique=True)),
                ('address', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Schedulled', 'Schedulled'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled'), ('Pending', 'Pending')], default='Schedulled', max_length=20)),
                ('appointment_no', models.CharField(editable=False, max_length=10)),
                ('appointment_time', models.TimeField()),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to='core.doctor')),
                ('Patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to='core.patient')),
            ],
            options={
                'unique_together': {('appointment_time', 'appointment_no', 'Doctor')},
            },
        ),
    ]
