# Generated by Django 6.0.2 on 2026-02-26 11:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_doctor_phone_alter_patient_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='User',
            new_name='user',
        ),
        migrations.AddField(
            model_name='patient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Quallification',
            field=models.CharField(max_length=50),
        ),
    ]
